// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/blog" | "/blog/[slug]" | "/docs" | "/docs/[slug]" | "/editor"
type AppRouteHandlerRoutes = "/api/cloud/assets/[name]" | "/api/cloud/assets/presign" | "/api/cloud/diagnose" | "/api/cloud/login" | "/api/cloud/logout" | "/api/cloud/project" | "/api/cloud/projects" | "/api/cloud/projects/[projectId]" | "/api/cloud/projects/[projectId]/assets/[hash]" | "/api/cloud/projects/[projectId]/assets/presign" | "/api/cloud/session" | "/blog/rss.xml"
type PageRoutes = never
type LayoutRoutes = "/" | "/blog" | "/docs"
type RedirectRoutes = "/[[...path]]"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[[...path]]": { "path"?: string[]; }
  "/admin": {}
  "/api/cloud/assets/[name]": { "name": string; }
  "/api/cloud/assets/presign": {}
  "/api/cloud/diagnose": {}
  "/api/cloud/login": {}
  "/api/cloud/logout": {}
  "/api/cloud/project": {}
  "/api/cloud/projects": {}
  "/api/cloud/projects/[projectId]": { "projectId": string; }
  "/api/cloud/projects/[projectId]/assets/[hash]": { "projectId": string; "hash": string; }
  "/api/cloud/projects/[projectId]/assets/presign": { "projectId": string; }
  "/api/cloud/session": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/blog/rss.xml": {}
  "/docs": {}
  "/docs/[slug]": { "slug": string; }
  "/editor": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/blog": never
  "/docs": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
