/*
 * GENERATED by scripts/generate-starter-projects.mjs.
 * Do not edit this file. Edit template_projects/*.cardgoblin.json and rerun
 * npm run generate:starter-projects instead.
 */

import type { GeneratedStarterProject } from "../_lib/starterProjects";

export const generatedStarterProjects = [
  {
    id: "poker-deck",
    label: "Poker Deck",
    suggestedName: "Poker Deck",
    sourceFile: "poker-deck.cardgoblin.json",
    available: false,
    load: null,
  },
  {
    id: "tcg",
    label: "TCG",
    suggestedName: "TCG",
    sourceFile: "tcg.cardgoblin.json",
    available: false,
    load: null,
  },
  {
    id: "party-game",
    label: "Party Game",
    suggestedName: "Party Game",
    sourceFile: "party-game.cardgoblin.json",
    available: false,
    load: null,
  },
] as const satisfies readonly GeneratedStarterProject[];
